# Required to run your project under the correct environment.
language: php
# Versions of PHP you want your project run with.
php:
 - 7.3
# Commands to be run before your environment runs.
before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev
notifications:
   on_success: never
   on_failure: always
cache:
 directories:
   - $HOME/.composer/cache/files
   - vendor
# Run script
script:
 - vendor/bin/phpunit tests --coverage-text
# After a build, send email notification with the build results
notifications:
 email: diego.gpl.free@gmail.com
