# Required to run your project under the correct environment.
language: php
# Versions of PHP you want your project run with.
php:
 - 7.3
 - hhvm
# Commands to be run before your environment runs.
before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev
# Commands you want to run that will verify your build.
script: phpunit
# fast_finish: If your build fails do not continue trying to build, just stop.
notifications:
   on_success: never
   on_failure: always
cache:
 directories:
   - $HOME/.composer/cache/files
# Install composer dependencies,
install:
 - composer install
# Run script
script:
 - vendor/bin/phpunit tests --coverage-text
# After a build, send email notification with the build results
notifications:
 email: diego.gpl.free@gmail.com
